/**
 * 12.16.8.3 - Assistant API Contract / Integration Gate.
 *
 * Purpose:
 *   Verify the real Assistant API request generated by the
 *   React application, without hard-coding a backend origin.
 *
 * Pipeline:
 *
 *   Browser
 *      ↓
 *   Assistant UI
 *      ↓
 *   configured API / proxy
 *      ↓
 *   POST /assistant/ask
 *      ↓
 *   AssistantResponse
 *      ↓
 *   answer + citations + metadata
 *
 * This file intentionally observes the actual request made by
 * the application. It does not construct a backend URL manually.
 */

import {
  test,
  expect,
  type Page,
  type Response,
} from "@playwright/test";

// ============================================================
// CONSTANTS
// ============================================================

const BASE_URL =
  process.env.E2E_BASE_URL ||
  "http://localhost:5173";

const ASSISTANT_PATH =
  "/assistant";

const ASSISTANT_QUESTION =
  "Chuyển đổi số";

const ASSISTANT_SECOND_QUESTION =
  "Triển khai chuyển đổi số";

// ============================================================
// TYPES
// ============================================================

interface AssistantCitation {
  citation_id?: string;
  source?: string;
  document_id?: string | null;
  page_number?: number | null;
  chunk_index?: number | null;
  content?: string;
  label?: string;
  [key: string]: unknown;
}

interface AssistantResponse {
  success?: boolean;
  answer?: string;
  question?: string;
  query?: string;
  citations?: AssistantCitation[];
  metadata?: Record<string, unknown>;
  message?: string;
  [key: string]: unknown;
}

// ============================================================
// HELPERS
// ============================================================

async function openAssistant(
  page: Page,
): Promise<void> {
  await page.goto(
    `${BASE_URL}${ASSISTANT_PATH}`,
    {
      waitUntil: "networkidle",
    },
  );

  await expect(
    page.locator("body"),
  ).toContainText(
    /Trợ lý Hành Chính AI|Trợ lý AI|Assistant/i,
  );
}

async function getAssistantInput(
  page: Page,
) {
  /*
   * Assistant UI dùng textarea.
   * Ưu tiên textarea để tránh bắt nhầm textbox
   * của navigation hoặc Knowledge Search.
   */
  const textarea =
    page.locator("textarea").first();

  if (
    (await textarea.count()) > 0 &&
    (await textarea.isVisible())
  ) {
    return textarea;
  }

  const textboxes =
    page.getByRole("textbox");

  const count =
    await textboxes.count();

  for (
    let index = count - 1;
    index >= 0;
    index -= 1
  ) {
    const textbox =
      textboxes.nth(index);

    if (
      await textbox.isVisible()
    ) {
      return textbox;
    }
  }

  throw new Error(
    "Không tìm thấy ô nhập câu hỏi Assistant.",
  );
}

async function submitAssistantQuestionAndCaptureResponse(
  page: Page,
  question: string,
): Promise<Response> {
  const input =
    await getAssistantInput(page);

  await input.fill(question);

  await expect(
    input,
  ).toHaveValue(question);

  const sendButton =
    page.getByRole(
      "button",
      {
        name: /gửi|send|hỏi/i,
      },
    ).first();

  await expect(
    sendButton,
  ).toBeVisible();

  await expect(
    sendButton,
  ).toBeEnabled();

  /*
   * Chờ đúng request mà UI thực hiện.
   * Không ghép host/backend URL thủ công.
   */
  const responsePromise =
    page.waitForResponse(
      (response) => {
        const url =
          response.url().toLowerCase();

        return (
          url.includes(
            "/assistant/ask",
          ) &&
          response.request().method() ===
            "POST"
        );
      },
      {
        timeout: 30_000,
      },
    );

  await sendButton.click();

  return responsePromise;
}

function isAssistantFallbackAnswer(
  answer: unknown,
): boolean {
  if (typeof answer !== "string") {
    return true;
  }

  const normalized =
    answer
      .trim()
      .toLowerCase();

  return (
    normalized.includes(
      "không tìm thấy thông tin phù hợp",
    ) ||
    normalized.includes(
      "tôi không tìm thấy thông tin phù hợp",
    ) ||
    normalized.includes(
      "không tìm thấy thông tin phù hợp trong tài liệu",
    )
  );
}


async function getAssistantResponseBodyWithRetry(
  page: Page,
  question: string,
  attempts: number = 3,
): Promise<{
  response: Response;
  body: AssistantResponse;
}> {
  let lastResult:
    | {
        response: Response;
        body: AssistantResponse;
      }
    | undefined;

  for (
    let attempt = 1;
    attempt <= attempts;
    attempt += 1
  ) {
    const result =
      await getAssistantResponseBody(
        page,
        question,
      );

    lastResult = result;

    /*
     * A fallback answer means the request itself succeeded,
     * but RAG did not return usable knowledge for this attempt.
     * Retry the real UI/API flow before declaring the integration
     * gate failed. No response is mocked or fabricated.
     */
    if (
      !isAssistantFallbackAnswer(
        result.body.answer,
      )
    ) {
      return result;
    }

    if (attempt < attempts) {
      await page.waitForTimeout(750);
    }
  }

  return lastResult!;
}


async function getAssistantResponseBody(
  page: Page,
  question: string =
    ASSISTANT_QUESTION,
): Promise<{
  response: Response;
  body: AssistantResponse;
}> {
  const response =
    await submitAssistantQuestionAndCaptureResponse(
      page,
      question,
    );

  const body =
    (await response.json()) as
      AssistantResponse;

  return {
    response,
    body,
  };
}

// ============================================================
// 12.16.8.3.1
// ASSISTANT API IS REACHABLE
// ============================================================

test(
  "12.16.8.3.1 - assistant API is reachable",
  async ({ page }) => {
    await openAssistant(page);

    const response =
      await submitAssistantQuestionAndCaptureResponse(
        page,
        ASSISTANT_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      response.ok(),
    ).toBeTruthy();
  },
);

// ============================================================
// 12.16.8.3.2
// ASSISTANT API RETURNS JSON
// ============================================================

test(
  "12.16.8.3.2 - assistant API returns JSON",
  async ({ page }) => {
    await openAssistant(page);

    const response =
      await submitAssistantQuestionAndCaptureResponse(
        page,
        ASSISTANT_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    const contentType =
      response.headers()[
        "content-type"
      ] || "";

    expect(
      contentType,
    ).toContain(
      "application/json",
    );
  },
);

// ============================================================
// 12.16.8.3.3
// ASSISTANT RESPONSE CONTRACT
// ============================================================

test(
  "12.16.8.3.3 - assistant response contract is valid",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    /*
     * AssistantResponse trong runtime hiện có
     * answer + query/question + citations + metadata.
     *
     * Một số backend version có thể dùng
     * "question" hoặc "query", nên chấp nhận cả hai.
     */
    expect(
      typeof body.answer,
    ).toBe("string");

    const returnedQuestion =
      body.question ??
      body.query;

    expect(
      typeof returnedQuestion,
    ).toBe("string");

    expect(
      Array.isArray(
        body.citations,
      ),
    ).toBeTruthy();

    expect(
      typeof body.metadata,
    ).toBe("object");

    expect(
      body.metadata,
    ).not.toBeNull();
  },
);

// ============================================================
// 12.16.8.3.4
// CITATION CONTRACT
// ============================================================

test(
  "12.16.8.3.4 - assistant citation contract is valid",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      Array.isArray(
        body.citations,
      ),
    ).toBeTruthy();

    /*
     * Nếu runtime có citation, kiểm tra đầy đủ metadata.
     * Không làm API contract phụ thuộc vào việc store có
     * dữ liệu hay không.
     */
    if (
      body.citations &&
      body.citations.length > 0
    ) {
      const citation =
        body.citations[0];

      expect(
        typeof citation,
      ).toBe("object");

      expect(
        citation,
      ).not.toBeNull();

      expect(
        citation.citation_id ||
          citation.label,
      ).toBeTruthy();

      expect(
        citation.source ||
          citation.document_id,
      ).toBeTruthy();

      if (
        citation.content !==
        undefined
      ) {
        expect(
          String(
            citation.content,
          ).trim().length,
        ).toBeGreaterThan(0);
      }
    }
  },
);

// ============================================================
// 12.16.8.3.5
// EXPECTED ASSISTANT KNOWLEDGE
// ============================================================

test(
  "12.16.8.3.5 - assistant returns relevant knowledge",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBodyWithRetry(
        page,
        ASSISTANT_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      typeof body.answer,
    ).toBe("string");

    /*
     * Với câu hỏi demo "Chuyển đổi số là gì?",
     * Assistant phải trả lời có nội dung liên quan.
     */
    expect(
      body.answer.trim().length,
    ).toBeGreaterThan(0);

    expect(
      isAssistantFallbackAnswer(
        body.answer,
      ),
    ).toBeFalsy();

    expect(
      body.answer,
    ).toMatch(
      /chuyển đổi số|công nghệ số|quản lý|dịch vụ/i,
    );
  },
);

// ============================================================
// 12.16.8.3.6
// API RESPONSE → UI
// ============================================================

test(
  "12.16.8.3.6 - assistant API data can render in UI",
  async ({ page }) => {
    await openAssistant(page);

    await submitAssistantQuestionAndCaptureResponse(
      page,
      ASSISTANT_QUESTION,
    );

    await expect(
      page.locator("body"),
    ).not.toContainText(
      /đang xử lý|loading/i,
      {
        timeout: 30_000,
      },
    );

    await expect(
      page.locator("body"),
    ).toContainText(
      /chuyển đổi số|công nghệ số|quá trình/i,
      {
        timeout: 30_000,
      },
    );
  },
);

// ============================================================
// 12.16.8.3.7
// FINAL ASSISTANT API GATE
// ============================================================

test(
  "12.16.8.3.7 - final assistant API gate",
  async ({ page }) => {
    const pageErrors: string[] = [];

    page.on(
      "pageerror",
      (error) => {
        pageErrors.push(
          error.message,
        );
      },
    );

    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
        ASSISTANT_SECOND_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      typeof body.answer,
    ).toBe("string");

    expect(
      body.answer.trim().length,
    ).toBeGreaterThan(0);

    const returnedQuestion =
      body.question ??
      body.query;

    expect(
      returnedQuestion,
    ).toBe(
      ASSISTANT_SECOND_QUESTION,
    );

    expect(
      Array.isArray(
        body.citations,
      ),
    ).toBeTruthy();

    expect(
      typeof body.metadata,
    ).toBe("object");

    expect(
      body.metadata,
    ).not.toBeNull();

    expect(
      pageErrors,
    ).toEqual([]);

    /*
     * Nội dung của câu hỏi thứ hai phải phản ánh
     * đúng Knowledge Base demo đã được kiểm thử ở 12.16.7.
     */
    expect(
      isAssistantFallbackAnswer(
        body.answer,
      ),
    ).toBeFalsy();

    expect(
      body.answer,
    ).toMatch(
      /cải cách hành chính|chất lượng phục vụ|người dân|doanh nghiệp|chuyển đổi số/i,
    );
  },
);