/**
 * 12.16.8.4 - Citation Flow / Citation Integration Gate.
 *
 * Purpose:
 *   Verify the complete citation flow of Hành Chính AI:
 *
 *   Browser
 *      ↓
 *   Assistant UI
 *      ↓
 *   POST /assistant/ask
 *      ↓
 *   RAG / Retrieval
 *      ↓
 *   CitationService
 *      ↓
 *   AssistantResponse.citations
 *      ↓
 *   Citation metadata rendered in UI
 *
 * Task 12.16.8.4
 *
 * Scope:
 *   - Citation API response
 *   - Citation list
 *   - Citation identity/source metadata
 *   - Citation document/page/chunk metadata
 *   - Citation metadata in AssistantResponse
 *   - Citation rendering in UI
 *   - Final citation stability gate
 *
 * This file observes the real request generated by the React
 * application. It does not construct a backend origin manually.
 */

import {
  test,
  expect,
  type Page,
  type Response,
} from "@playwright/test";

// ============================================================
// CONSTANTS
// ============================================================

const BASE_URL =
  process.env.E2E_BASE_URL ||
  "http://localhost:5173";

const ASSISTANT_PATH = "/assistant";

const CITATION_QUESTION =
  "Chuyển đổi số là gì?";

const CITATION_SECOND_QUESTION =
  "Triển khai chuyển đổi số cần gắn với những nội dung nào?";

// ============================================================
// TYPES
// ============================================================

interface AssistantCitation {
  citation_id?: string;
  source?: string;
  document_id?: string | null;
  page_number?: number | null;
  chunk_index?: number | null;
  content?: string;
  label?: string;
  score?: number | null;
  metadata?: Record<string, unknown>;
  [key: string]: unknown;
}

interface AssistantResponse {
  success?: boolean;
  answer?: string;
  question?: string;
  query?: string;
  citations?: AssistantCitation[];
  metadata?: Record<string, unknown>;
  message?: string;
  [key: string]: unknown;
}

// ============================================================
// HELPERS
// ============================================================

async function openAssistant(
  page: Page,
): Promise<void> {
  await page.goto(
    `${BASE_URL}${ASSISTANT_PATH}`,
    {
      waitUntil: "networkidle",
    },
  );

  await expect(
    page.locator("body"),
  ).toContainText(
    /Trợ lý Hành Chính AI|Trợ lý AI|Assistant/i,
  );
}

async function getAssistantInput(
  page: Page,
) {
  const textarea =
    page.locator("textarea").first();

  if (
    (await textarea.count()) > 0 &&
    (await textarea.isVisible())
  ) {
    return textarea;
  }

  const textboxes =
    page.getByRole("textbox");

  const count =
    await textboxes.count();

  for (
    let index = count - 1;
    index >= 0;
    index -= 1
  ) {
    const textbox =
      textboxes.nth(index);

    if (
      await textbox.isVisible()
    ) {
      return textbox;
    }
  }

  throw new Error(
    "Không tìm thấy ô nhập câu hỏi Assistant.",
  );
}

async function submitAssistantQuestionAndCaptureResponse(
  page: Page,
  question: string,
): Promise<Response> {
  const input =
    await getAssistantInput(page);

  await input.fill(question);

  await expect(
    input,
  ).toHaveValue(question);

  const sendButton =
    page.getByRole(
      "button",
      {
        name: /gửi|send|hỏi/i,
      },
    ).first();

  await expect(
    sendButton,
  ).toBeVisible();

  await expect(
    sendButton,
  ).toBeEnabled();

  const responsePromise =
    page.waitForResponse(
      (response) => {
        const url =
          response.url().toLowerCase();

        return (
          url.includes("/assistant/ask") &&
          response.request().method() ===
            "POST"
        );
      },
      {
        timeout: 30_000,
      },
    );

  await sendButton.click();

  return responsePromise;
}

async function getAssistantResponseBody(
  page: Page,
  question: string = CITATION_QUESTION,
): Promise<{
  response: Response;
  body: AssistantResponse;
}> {
  const response =
    await submitAssistantQuestionAndCaptureResponse(
      page,
      question,
    );

  const body =
    (await response.json()) as AssistantResponse;

  return {
    response,
    body,
  };
}

function getCitations(
  body: AssistantResponse,
): AssistantCitation[] {
  expect(
    Array.isArray(body.citations),
  ).toBeTruthy();

  return body.citations ?? [];
}

function getCitationCount(
  body: AssistantResponse,
): number {
  const citations =
    getCitations(body);

  return citations.length;
}

// ============================================================
// 12.16.8.4.1
// CITATION FLOW IS REACHABLE
// ============================================================

test(
  "12.16.8.4.1 - citation flow is reachable",
  async ({ page }) => {
    await openAssistant(page);

    const response =
      await submitAssistantQuestionAndCaptureResponse(
        page,
        CITATION_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      response.ok(),
    ).toBeTruthy();
  },
);

// ============================================================
// 12.16.8.4.2
// CITATIONS ARE RETURNED
// ============================================================

test(
  "12.16.8.4.2 - assistant returns citations",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    const citations =
      getCitations(body);

    /*
     * Citation Flow task yêu cầu Knowledge/RAG
     * có ít nhất một nguồn được chuyển tới
     * AssistantResponse.
     */
    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);
  },
);

// ============================================================
// 12.16.8.4.3
// CITATION IDENTITY / SOURCE
// ============================================================

test(
  "12.16.8.4.3 - citation identity and source are valid",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    const citations =
      getCitations(body);

    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);

    const citation =
      citations[0];

    expect(
      citation,
    ).toBeTruthy();

    expect(
      citation.citation_id ||
        citation.label,
    ).toBeTruthy();

    expect(
      citation.source ||
        citation.document_id,
    ).toBeTruthy();

    expect(
      typeof citation,
    ).toBe("object");
  },
);

// ============================================================
// 12.16.8.4.4
// CITATION DOCUMENT / PAGE / CHUNK METADATA
// ============================================================

test(
  "12.16.8.4.4 - citation document metadata is preserved",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    const citations =
      getCitations(body);

    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);

    const citation =
      citations[0];

    /*
     * CitationService của pipeline Knowledge
     * phải giữ lại metadata nguồn để UI có thể
     * truy nguyên tài liệu.
     */
    expect(
      citation.document_id ||
        citation.source,
    ).toBeTruthy();

    expect(
      citation.page_number,
    ).not.toBeUndefined();

    expect(
      citation.chunk_index,
    ).not.toBeUndefined();

    if (
      citation.content !==
      undefined
    ) {
      expect(
        String(
          citation.content,
        ).trim().length,
      ).toBeGreaterThan(0);
    }
  },
);

// ============================================================
// 12.16.8.4.5
// CITATION SCORE / METADATA
// ============================================================

test(
  "12.16.8.4.5 - citation score and metadata are valid",
  async ({ page }) => {
    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
      );

    expect(
      response.status(),
    ).toBe(200);

    const citations =
      getCitations(body);

    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);

    const citation =
      citations[0];

    /*
     * Score là metadata similarity của nguồn.
     * Một số runtime có thể expose score ở
     * citation hoặc metadata; không ép kiểu
     * quá mức để giữ compatibility.
     */
    if (
      citation.score !==
      undefined &&
      citation.score !== null
    ) {
      expect(
        typeof citation.score,
      ).toBe("number");
    }

    if (
      citation.metadata !==
      undefined
    ) {
      expect(
        typeof citation.metadata,
      ).toBe("object");

      expect(
        citation.metadata,
      ).not.toBeNull();
    }

    expect(
      typeof body.metadata,
    ).toBe("object");

    expect(
      body.metadata,
    ).not.toBeNull();

    const citationCount =
      body.metadata?.citation_count;

    if (
      citationCount !==
        undefined &&
      citationCount !== null
    ) {
      expect(
        Number(citationCount),
      ).toBeGreaterThanOrEqual(1);
    }
  },
);

// ============================================================
// 12.16.8.4.6
// CITATION IS RENDERED IN UI
// ============================================================

test(
  "12.16.8.4.6 - citation data is rendered in UI",
  async ({ page }) => {
    await openAssistant(page);

    const response =
      await submitAssistantQuestionAndCaptureResponse(
        page,
        CITATION_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    const body =
      (await response.json()) as AssistantResponse;

    const citations =
      getCitations(body);

    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);

    /*
     * Chờ Assistant hoàn tất render.
     */
    await expect(
      page.locator("body"),
    ).not.toContainText(
      /đang xử lý|loading/i,
      {
        timeout: 30_000,
      },
    );

    /*
     * UI phải hiển thị ít nhất một dấu hiệu
     * của citation/source. Không hard-code một
     * class CSS cụ thể.
     */
    await expect(
      page.locator("body"),
    ).toContainText(
      /nguồn|trích dẫn|citation|tài liệu|tham khảo/i,
      {
        timeout: 30_000,
      },
    );

    const citation =
      citations[0];

    const sourceText =
      citation.source ||
      citation.document_id ||
      citation.label;

    if (sourceText) {
      await expect(
        page.locator("body"),
      ).toContainText(
        String(sourceText),
        {
          timeout: 30_000,
        },
      );
    }
  },
);

// ============================================================
// 12.16.8.4.7
// FINAL CITATION FLOW GATE
// ============================================================

test(
  "12.16.8.4.7 - final citation flow gate",
  async ({ page }) => {
    const pageErrors: string[] = [];

    page.on(
      "pageerror",
      (error) => {
        pageErrors.push(
          error.message,
        );
      },
    );

    await openAssistant(page);

    const {
      response,
      body,
    } =
      await getAssistantResponseBody(
        page,
        CITATION_SECOND_QUESTION,
      );

    expect(
      response.status(),
    ).toBe(200);

    expect(
      response.ok(),
    ).toBeTruthy();

    expect(
      typeof body.answer,
    ).toBe("string");

    expect(
      body.answer.trim().length,
    ).toBeGreaterThan(0);

    const returnedQuestion =
      body.question ??
      body.query;

    expect(
      returnedQuestion,
    ).toBe(
      CITATION_SECOND_QUESTION,
    );

    const citations =
      getCitations(body);

    expect(
      citations.length,
    ).toBeGreaterThanOrEqual(1);

    for (
      const citation of citations
    ) {
      expect(
        typeof citation,
      ).toBe("object");

      expect(
        citation,
      ).not.toBeNull();

      expect(
        citation.citation_id ||
          citation.label,
      ).toBeTruthy();

      expect(
        citation.source ||
          citation.document_id,
      ).toBeTruthy();

      if (
        citation.content !==
        undefined
      ) {
        expect(
          String(
            citation.content,
          ).trim().length,
        ).toBeGreaterThan(0);
      }
    }

    expect(
      typeof body.metadata,
    ).toBe("object");

    expect(
      body.metadata,
    ).not.toBeNull();

    const citationCount =
      body.metadata?.citation_count;

    if (
      citationCount !==
        undefined &&
      citationCount !== null
    ) {
      expect(
        Number(citationCount),
      ).toBeGreaterThanOrEqual(1);
    }

    expect(
      pageErrors,
    ).toEqual([]);
  },
);